### ISSUE TITLE
[1.0] Spinner is broken when text direction is RTL

### ISSUE THREAD

**Issue by dzhioev** [PolymerElements/paper-spinner#16]
Browser: Google Chrome 42.0.2311.153 (Official Build) (64-bit)
That is how it looks like:
![Broken spinner](http://dzhioev.net:8080/spinner.png)
Demo page: http://dzhioev.net:8080/spinner_rtl.html

[Material design spec](http://www.google.com/design/spec/usability/bidirectionality.html#bidirectionality-rtl-mirroring-guidelines) says that we shouldn't mirror the spinner (as it runs clock-wise), so I think adding 'direction: ltr;' to :host is a proper fix for the issue.

**Comment by notwaldorf** [comment]
I don't think we've had a lot of time to address RTL issues before 1.0, but I'll take a look at it now.

**Comment by ConAntonakos** [comment]
This is exactly how the spinner looks like for me in Firefox. Any issues there?

**Comment by notwaldorf** [comment]
@ConAntonakos do you mean in the link Pavel posted, or in the catalog (https://elements.polymer-project.org/elements/paper-spinner?view=demo:demo/index.html)? The latest version of the spinner _should_ look fine, RTL or not, on all browsers,
