### ISSUE TITLE
[1.0] Spinner is broken in Firefox

### ISSUE THREAD

**Issue by ConAntonakos** [PolymerElements/paper-spinner#25]
Spinner is completely broken in Firefox with barely any custom CSS applied to it. 

![screen shot 2015-07-14 at 12 48 16 pm](https://cloud.githubusercontent.com/assets/1504302/8679169/11cda520-2a27-11e5-9273-ba53694e231b.png)
![screen shot 2015-07-14 at 12 51 52 pm](https://cloud.githubusercontent.com/assets/1504302/8679188/2adbbade-2a27-11e5-8450-e476d2c49090.png)

Similar to https://github.com/PolymerElements/paper-spinner/issues/16.

**Comment by notwaldorf** [comment]
@ConAntonakos Do you have a jsbin with a repro case? This is what I see in Firefox in the [demo](https://elements.polymer-project.org/elements/paper-spinner?view=demo:demo/index.html):
<img width="544" alt="screen shot 2015-07-14 at 10 07 31 am" src="https://cloud.githubusercontent.com/assets/1369170/8679553/28df65d0-2a10-11e5-8a80-4efd1bb8d975.png">

**Comment by ConAntonakos** [comment]
Thanks for responding, @notwaldorf. Really weird bug. So, I tested it again, and it's working fine now. But the reason it was broken in the first place was because I had included the `paper-spinner` in the following `template` HTML:
```
<template>
  <paper-dialog id="dialog" class="unselectable"
    exit-animation="fade-out-animation"
    modal="true"
    >
    <!-- <paper-spinner active></paper-spinner> -->
    <section id='dialog-form'>
      <article id="dialog-content">
      </article>
      <article id="dialog-buttons">
        <paper-button raised dismiss>Cancel</paper-button>
        <paper-button raised confirm type="submit" class="colored pull-right">Confirm</paper-button>
      </article>
    </section>
  </paper-dialog>
</template>
```

Which I was then appending to the main document:
```
    var link = document.querySelector('link[rel="import"][href*="dialog.html"]');
    var dialog = document.getElementById('dialog');
    
    if(!dialog){
      var content = link.import;
      var template = content.querySelector('template');
      var clone = document.importNode(template.content, true);

      var node = document.body
      node.appendChild(clone);

      dialog = document.getElementById('dialog');
    }
```

For whatever reason, this broke the `paper-spinner` in Firefox, but not in Chrome.

**Comment by notwaldorf** [comment]
@ConAntonakos Does your code snippet work fine now, though?

**Comment by ConAntonakos** [comment]
So, I tried to dynamically add the `paper-spinner` to the `paper-dialog` after the dialog had been imported, and I'm still getting that funky behavior. It's only happening within the `paper-dialog`. Really odd... :crying_cat_face:

**Comment by notwaldorf** [comment]
Ah, it might be some sorcery about the absolute positioning of the `paper-spinner`. I'll take a look

**Comment by glaucomunsberg** [comment]
Something like this occurred with me, but in Google Chrome

````
<paper-drawer-panel>
  <paper-header-panel drawer>
    <paper-toolbar>
      <div>Application</div>
    </paper-toolbar>
    <div> Drawer content... </div>
  </paper-header-panel>
  <paper-header-panel main>
    <paper-toolbar>
      <paper-icon-button icon="menu" paper-drawer-toggle></paper-icon-button>
        <paper-spinner active></paper-spinner>
      <div>Title</div>
    </paper-toolbar>
    <div> Main content... </div>
  </paper-header-panel>
</paper-drawer-panel>
````
![screenshot from 2015-08-12 19-30-44](https://cloud.githubusercontent.com/assets/1040010/9238473/e3169354-4128-11e5-9d91-20e217df9341.png)

**Comment by GutoMotta** [comment]
I'm having a similar issue here, maybe the same. The spinner is shown but broken. This happens both on Google Chrome 44.0.2403.155 and on Firefox 39.0, both on my Ubuntu 14.10. I've made a test on another computer (also a Ubuntu 14.10), same issue there.

![screenshot_spinner_bug](https://cloud.githubusercontent.com/assets/11479274/9281963/726e018c-429f-11e5-9506-9ec5f6e1c0a9.png)

I'm inserting the spinner through javascript, but also tried to put it there statically and the same thing happened.

**Comment by glaucomunsberg** [comment]
@GutoMotta I think the same, I'm using the same chrome, firefox and the versions they are the same.

**Comment by bicknellr** [comment]
These seem to be two separate issues: the original one (as posted by @ConAntonakos) where the spinner is all sorts of wrong, and another (from @GutoMotta and @glaucomunsberg's comments) where the spinner appears to be split in half.

I can repro the first, but not without doing some pretty weird stuff. So far, the closest I've been able to get is by forcing `iron-meta.html` to 404 while also cloning and appending the contents of a template into the document on a timed interval on load:
```html
<template>
  <paper-dialog>
    <paper-spinner active></paper-spinner>
  </paper-dialog>
</template>
```
...which results in about half of the spinners being visible inside of an unopened dialog and looking like this:

![screen shot 2015-10-27 at 5 11 04 pm](https://cloud.githubusercontent.com/assets/406614/10776341/bef95782-7ccd-11e5-907d-99d2a42ec6ae.png)

Maybe this is a race between the HTML Imports polyfill and your custom loading mechanism? If `iron-meta.html` hasn't loaded and you try to create a `paper-dialog` - for example, by importing the content of a template containing one - it will throw. As long as you're loading the polyfill, you can *wait for the `WebComponentsReady` event* to be fired on `window` and you'll know that the imports have finished loading.


The second issue looks like the `div` containing the second half of the circle is wrapping. I can't actually repro this one, but if you change the width in the `.circle-clipper` rule from `50%` to `51%`, it will cause this behavior. Adding `white-space: nowrap;` to the `.spinner-layer` rule should fix it. (I'll post a PR for this soon.)

**Comment by bicknellr** [comment]
Given that #34 (which fixes the split spinner problem) has been merged and the original issue seems to be solved by waiting on the `WebComponentsReady` event, I'm going to close this out. @ConAntonakos, feel free to reopen if you see this again after trying out the event.
