### ISSUE TITLE
Spinner flickering in Chrome 46

### ISSUE THREAD

**Issue by wq9** [PolymerElements/paper-spinner#26]
![image](http://i.gyazo.com/c797c264de9c5b604b95b6e5b7545a6e.gif)

The spinner appears like above on Google Chrome Version 46.0.2457.0 canary (64-bit) and Windows 10.

The spinner looks fine in Chrome v43 and Firefox.

**Comment by notwaldorf** [comment]
Oh wow, thanks for reporting this. We haven't changed the spinner code, so I'll try to figure out what Chrome is doing that's new :(

**Comment by notwaldorf** [comment]
I think this was automagically fixed in Chrome. It looks fine on 46.0.2466.0.
