### ISSUE TITLE
Declaratively resetting the spinner before activating it again

### ISSUE THREAD

**Issue by urandom** [PolymerElements/paper-spinner#27]
It doesn't look like you can reuse a spinner declaratively once you've deactivated it.
If you have something like:
```html
<paper-spinner active="[[ loading ]]"></paper-spinner>
```
once the spinner is inactive, it will go into cooldown. If the loading property changes, you won't be able to see the spinner anymore because the _coolDown property is still true.

**Comment by bpinney** [comment]
Any update on this?

**Comment by samccone** [comment]
cc @notwaldorf
