### ISSUE TITLE
paper-spinner not working in IE

### ISSUE THREAD

**Issue by kungufli** [PolymerElements/paper-spinner#31]
`paper-spinner` don't work at all in IE browser. You can check it by visiting the demo page https://elements.polymer-project.org/elements/paper-spinner?view=demo:demo/index.html from IE 11

**Comment by bicknellr** [comment]
I think the issue you're seeing here is really an issue with the interaction between the catalog and demo pages rather than the `paper-spinner` itself. If you go to http://polygit.org/components/paper-spinner/demo/index.html in IE11 you should see the spinners load.

**Comment by kungufli** [comment]
@bicknellr thanks, you're right. I didn't notice because I have a spinner that doesn't work on IE in my project, but it's for some other reason I still had to find.

**Comment by bicknellr** [comment]
Also, there's an issue with polygit at the moment that causes (at least) that demo not to work on occasion: https://github.com/PolymerLabs/polygit/issues/3

**Comment by L-u-k-e** [comment]
I'm not sure what exactly was happening a month ago. However, If you look at the demo now, you'll see that it sort of works, but everything looks shaky. It's not specific to the catalog as the same issue is occurring on a personal project of mine.

**Comment by kungufli** [comment]
Still not found what's was causing the issue, but it seems fixed now in the last version of the element.
