### ISSUE TITLE
Spinner is broken

### ISSUE THREAD

**Issue by glaucomunsberg** [PolymerElements/paper-spinner#38]
Similar problem we (I and @GutoMotta) report at issue #25, I wait the webcomponentsready but now this happens:
![screen shot 2015-11-07 at 7 13 00 pm](https://cloud.githubusercontent.com/assets/1040010/11017377/155efc4e-8584-11e5-9fcd-a7cba801ce52.png)
![screen shot 2015-11-07 at 7 13 12 pm](https://cloud.githubusercontent.com/assets/1040010/11017378/1560777c-8584-11e5-9fa3-a3c3396d7fdd.png)
![screen shot 2015-11-07 at 7 13 17 pm](https://cloud.githubusercontent.com/assets/1040010/11017379/156c4868-8584-11e5-8a57-b68ac7a1b841.png)

@gutoMotta can you confirm if happens with you

**Comment by bicknellr** [comment]
There's a small div that sits above the two halves of the circle to make sure there's no space between them - it has the class `gap-patch`. Could you inspect it and tell me what its CSS display and position properties are? It looks like some styles from somewhere else might be leaking in. Also, a JSBin reproducing the issue is always appreciated! :)

**Comment by glaucomunsberg** [comment]
@bicknellr of course, a send here the image with the styles. Well I'm using a lot of elements on my project, the most of elements created by you. The same problem happens with the paper-spinner-lite
![screen shot 2015-12-24 at 4 01 28 pm](https://cloud.githubusercontent.com/assets/1040010/11997033/63b4d762-aa58-11e5-9005-2a441718669e.png)

**Comment by keanulee** [comment]
@glaucomunsberg I am trying to reproduce this issue by creating a similar tree structure to your project, but I am still not seeing the issue. Could you take a look at my code sample and see if you can reproduce this problem? http://jsbin.com/buhosozaco/edit?html,output

**Comment by glaucomunsberg** [comment]
Hi @keanulee I can't reproduce the problem, for some reason, when I use a lot of elements that this happens. Look down the elements, now I have 6 projects inside of this problem and all of them got the same issue. apparently no style was injected in the paper-spinner. I do not know what to do. any tips? 😌
```
//= require polymer/polymer
//= require paper-styles/paper-styles
//= require paper-drawer-panel/paper-drawer-panel
//= require paper-header-panel/paper-header-panel
//= require paper-toolbar/paper-toolbar
//= require paper-menu/paper-menu
//= require paper-menu/paper-submenu
//= require paper-item/paper-item
//= require paper-item/paper-item-body
//= require paper-icon-button/paper-icon-button
//= require paper-spinner/paper-spinner
//= require paper-tooltip/paper-tooltip
//= require paper-material/paper-material
//= require paper-input/paper-input
//= require paper-input/paper-textarea
//= require paper-dialog/paper-dialog
//= require paper-dialog-behavior/paper-dialog-behavior
//= require paper-dialog-scrollable/paper-dialog-scrollable
//= require paper-fab/paper-fab
//= require paper-ripple/paper-ripple
//= require paper-checkbox/paper-checkbox
//= require paper-button/paper-button
//= require paper-toast/paper-toast
//= require paper-tabs/paper-tabs
//= require paper-item/paper-icon-item
//= require paper-radio-group/paper-radio-group
//= require paper-radio-button/paper-radio-button
//= require paper-dropdown-menu/paper-dropdown-menu
//= require paper-scroll-header-panel/paper-scroll-header-panel
//= require paper-card/paper-card
//= require paper-badge/paper-badge
//= require paper-progress/paper-progress

//= require iron-dropdown/iron-dropdown
//= require iron-collapse/iron-collapse
//= require iron-pages/iron-pages
//= require iron-image/iron-image
//= require iron-icon/iron-icon
//= require iron-icons/iron-icons
//= require iron-icons/editor-icons
//= require iron-icons/av-icons
//= require iron-icons/notification-icons
//= require iron-icons/social-icons
//= require iron-icons/communication-icons
//= require iron-icons/hardware-icons
//= require iron-icons/image-icons
//= require iron-icons/maps-icons
//= require iron-flex-layout/iron-flex-layout
//= require iron-a11y-keys/iron-a11y-keys

//= require font-roboto/roboto

//= require gold-phone-input/gold-phone-input
```

**Comment by keanulee** [comment]
@glaucomunsberg I tried including all those imports and imperatively inserting the spinner on `WebComponentsReady`, but I still can't reproduce this issue. Can you provide a code sample that has this issue? http://jsbin.com/letowahefe/edit?html,output

**Comment by glaucomunsberg** [comment]
@keanulee I guess that is a problem at my project atHome, the problem happens only on the projects derived from atHome. So, I will close the issue. Thanks for your attention
