### ISSUE TITLE
Mix spinner with floating action button

### ISSUE THREAD

**Issue by tpluscode** [PolymerElements/paper-spinner#42]
Hi. The [material design guidelines](https://www.google.com/design/spec/components/progress-activity.html#progress-activity-types-of-indicators) show an example of combining spinner with a FAB, which produces a nice effect. 

Is it possible with Polymer's paper elements? Is there an example somewhere?

**Comment by keanulee** [comment]
We don't have a documented example, but you can definitely use CSS to position a `<paper-fab>` above a `<paper-spinner>` to achieve a similar effect. I posted an example at http://jsbin.com/cuwotaniku/edit?html,output

Let us know if this works for you.

**Comment by tpluscode** [comment]
So simple. Thank you for posting the example!
