### ISSUE TITLE
paper-spinner still takes up space when not active

### ISSUE THREAD

**Issue by cdata** [PolymerElements/paper-spinner#48]
_From @lesliana on March 31, 2016 19:12_

When the paper-spinner is not active, it is aria-hidden and its children have opacity:0, but the <paper-spinner> element itself is still display:inline-block and takes up space (by default, 28x28px).

This means that a user who is trying to click on an element behind the invisible spinner could end up clicking on the spinner, so their click on the element won't appear to work.  The spinner should have display:none or be equivalently hidden and not take up any space when it's inactive.

_Copied from original issue: Polymer/polymer#3549_

**Comment by rictic** [comment]
I can see both options as being useful in some situations. Making this would be disruptive to existing layouts though, and there's a number of pretty easy work arounds when you want it to be totally gone from the layout. For example, I think this would work:

```html
<style>
  paper-spinner[active] {
    display: block;
  }
  paper-spinner {
    display: none;
  }
</style>
<paper-spinner active$="{{shouldBeActive}}">
</paper-spinner>
```

**Comment by keanulee** [comment]
Toggling `visibility` would probably be a better solution - that should prevent it from being clickable. Toggling `display` would cause layout if the spinner isn't position absolutely, which seems like an unnecessary overhead.

**Comment by keanulee** [comment]
Alternatively, if the paper-spinner element will never receive a pointer event, you can just style it `pointer-events: none;`

**Comment by keanulee** [comment]
The above suggestion to use `pointer-events: none` was sufficient.

**Comment by stat92** [comment]
If your spinner will toggle regularly it will work with this properties well:
     ```
      paper-spinner[aria-hidden] {
        display: none;
      }
      paper-spinner:not([aria-hidden]) {
        display: inline-block;
      }
```
