### ISSUE TITLE
how to display the spinner on center by fading the background screen ?

### ISSUE THREAD

**Issue by sowsan** [PolymerElements/paper-spinner#52]
Was looking for something like this thread talks : http://stackoverflow.com/questions/6091253/overlay-with-spinner

Any idea how can I achieve it with the kind of styling we ahve with paper-spinner ?

**Comment by keanulee** [comment]
You can do something like this: http://jsbin.com/qajavo/edit?html,output

**Comment by sowsan** [comment]
thank you so much:)
