### ISSUE TITLE
<template strip-whitespace> is performance issue

### ISSUE THREAD

**Issue by JosefJezek** [PolymerElements/paper-spinner#53]
Better solution is flex container...

```css
.spinner-layer {
  display: flex;
}
```

#UseThePlatform ;-)

**Comment by keanulee** [comment]
Ah yes, now that `.gap-patch` has been moved to a pseudo `::after` element, we should be able to use flexbox. Thanks.

**Comment by keanulee** [comment]
@JosefJezek Do you have evidence that `strip-whitespace` is a performance setback? I just learned that `strip-whitespace` was added as a performance enhancement https://www.polymer-project.org/1.0/docs/devguide/local-dom#strip-whitespace

**Comment by JosefJezek** [comment]
JS is slowly then CSS... ;-)

```js
// optionally strip whitespace
            if (stripWhiteSpace && !node.textContent.trim()) {
              root.removeChild(node);
              // decrement index since node is removed
              i--;
            }
```

https://github.com/Polymer/polymer/blob/edb59eb6283074ce54f374b30b884c9f9fcf9f5f/src/lib/annotations/annotations.html#L249

**Comment by notwaldorf** [comment]
@JosefJezek `strip-whitespace` removes _all_ the whitespace in the template, not just the one in between the elements you care about, which makes the entire file smaller and faster to download. Also, this is done once, at registration time, so it's not really a huge performance hit per element.

**Comment by JosefJezek** [comment]
@notwaldorf Thank you :smiling_imp:
