### ISSUE TITLE
Paper spinner not displaying properly in Chrome

### ISSUE THREAD

**Issue by rkief** [PolymerElements/paper-spinner#56]
Viewing the paper-spinner demo from the catalog:
https://elements.polymer-project.org/elements/paper-spinner?view=demo:demo/index.html

Only the leading edge of the spinner displays.  Works fine in FF and IE11.

![paperspinner](https://cloud.githubusercontent.com/assets/6942327/16743192/28c902ea-4779-11e6-814f-5f2130189e05.PNG)

### Browsers Affected

- [X] Chrome Version 53.0.2785.8 dev-m (64-bit)
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by keanulee** [comment]
Appears to be a browser bug that affects animation on pseudo `::after` elements (repro http://jsbin.com/bokipev/edit?html,output) - see https://bugs.chromium.org/p/chromium/issues/detail?id=626571

**Comment by keanulee** [comment]
This issue seems to be fixed in the latest version of Chrome Canary, so I'm marking it as fixed.

**Comment by ShaggyDude** [comment]
Getting this same problem in Safari mac now.
