### ISSUE TITLE
Spinners are rendered as rounded squares, not circles.

### ISSUE THREAD

**Issue by ElsewhereGames** [PolymerElements/paper-spinner#59]
### Description

Spinners are no longer rendering as circles, rather, they appear to be rounded squares.

### Expected outcome

Spinners are circular.

### Actual outcome

![image](https://cloud.githubusercontent.com/assets/824558/18731904/f6917464-8013-11e6-8b03-d42d796c4ff7.png)

Spinners are rounded squares.

### Live Demo

https://elements.polymer-project.org/elements/paper-spinner?view=demo:demo/index.html&active=paper-spinner

### Steps to reproduce

Navigate to live demo using Chrome, see rendering issue.

### Browsers Affected

- [x] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [x] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by keanulee** [comment]
Cannot reproduce on Chrome 53.0.2785.116 on OS X El Capitan (they're just elements with `border-radius: 50%;`) - please specify a more specific version.

![image](https://cloud.githubusercontent.com/assets/1319720/18732762/a65ecfee-801a-11e6-9a65-95880078af48.png)

**Comment by ElsewhereGames** [comment]
Same version (53.0.2785.116 m) but on Windows 10. Hmm, perhaps it is the odd scaling applied to the secondary monitor.

**Comment by ElsewhereGames** [comment]
Yeah, it is not an issue on my laptop's primary monitor after a refresh. Odd.
