### ISSUE TITLE
Default colours not working?

### ISSUE THREAD

**Issue by zerodevx** [PolymerElements/paper-spinner#6]
Hi, the default colours doesn't seem to be working for me. I'm simply using
```
<paper-spinner active></paper-spinner>
```
In order to make the 4 layers to show different colours, I have to define a 
```
<style is="custom-style">
    --paper-spinner-layer-1-color: #4285f4;
    --paper-spinner-layer-2-color: #db4437;
    --paper-spinner-layer-3-color: #f4b400;
    --paper-spinner-layer-4-color: #0f9d58;    
</style>
```
outside, from my calling element.

Is something wrong?

**Comment by notwaldorf** [comment]
Thanks for spotting this! I'll merge the fix asap :)
