### ISSUE TITLE
paper-spinner-lite causes rest of the page to spin

### ISSUE THREAD

**Issue by adam-azarchs-10x** [PolymerElements/paper-spinner#65]
### Description

When paper-spinner first starts spinning, it briefly causes containing elements to spin around the middle of the spinner.  It's hard to notice on a fast system, and doesn't trigger reliably, but I suspect that the css animation is sometimes briefly binding to the wrong element.

### Expected outcome

The rest of the page stays put.

### Actual outcome

Parts of the page which are not the spinner start spinning.

### Steps to reproduce
The "toggle" button in the demo can trigger it, particularly if the debugger is active, but it can be made to trigger more reliably with some minor modifications:

1. In the first panel (line 43 of the demo) remove all of the spinners except for one `paper-spinner-lite` (the inactive one).

2. Modify the `toggle` function, at around line 89, to add
```javascript
spinner.active = !spinner.active;
p = new Promise(function() {
  return setTimeout(function() {
    spinner.active = !spinner.active;
    alert("foo");
  }, 10);
});
```

3. Open the demo and click the toggle button.  Most of the time (but not every time) the code panel below the spinner will start spinning with the spinner until the alert is closed.

### Browsers Affected

- [X] Chrome (linux 57.0.2987.54 beta)
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by keanulee** [comment]
Seems like a Chrome bug. I'm able to repro this with Chrome 56 on macOS 10.12. Will investigate further and try to reduce it to a smaller demo.

**Comment by shaper** [comment]
Hi, as we look into this it could be helpful to have a test case that does not require clicking a button. Do you have a sample page using Polymer or otherwise that demonstrates the issue even if it happens less reliably?

**Comment by shaper** [comment]
Actually trchen@ looks like he just created one, see http://jsbin.com/voporukeve

**Comment by keanulee** [comment]
The Chrome bug (https://bugs.chromium.org/p/chromium/issues/detail?id=695125) appears to be fixed now
