### ISSUE TITLE
Paper spinner not displaying properly in Safari see #56

### ISSUE THREAD

**Issue by ShaggyDude** [PolymerElements/paper-spinner#68]
### Description
Spinner just shows the initial small arc on Safari

### Expected outcome

Spinner arc should grow.

### Actual outcome

Spinner arc rotates but does not grow in length

### Live Demo
https://www.webcomponents.org/element/PolymerElements/paper-spinner

### Steps to reproduce

1. go to https://www.webcomponents.org/element/PolymerElements/paper-spinner in safari mac

### Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [x] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

### Notes

This is the same issue as except it is showing up only in Safari #56

**Comment by keanulee** [comment]
WebKit bug: https://bugs.webkit.org/show_bug.cgi?id=173027

**Comment by dshukertjr** [comment]
Is this going to be fixed anytime soon, because webkit does not seem to be on to it.

**Comment by NovapaX** [comment]
Is there a way to implement a fix or workaround for this somehow, for the time being?

**Comment by aryashashank** [comment]
Still not fixed. Any workaround to the problem?

**Comment by aryashashank** [comment]
Fixed: https://github.com/PolymerElements/paper-spinner/pull/82
