### ISSUE TITLE
Message page and spinner will not come in MAC OS / Safari

### ISSUE THREAD

**Issue by rickvidallon** [PolymerElements/paper-spinner#69]
Over ANY version of MAC OS the payment processing spinner message page DOES NOT come using Safari. 
Example: http://homegrownusa.club/mac/MACOS-Safari.mp4
Is suppose to display this: http://homegrownusa.club/mac/spinner.jpg

Works great in Firefox, IE, Chrome or ALL MAC OS and WIN 7/10
http://homegrownusa.club/mac/MACOS-Firefox.mp4

Will not work in any MAC OS with any Safari browser.

Any suggestions or direction appreciated greatly. 

### Browsers Affected
- [x] Safari 9
- [x] Safari 8
- [x] Safari 7

**Comment by keanulee** [comment]
This is not the right place for this issue - we are not associated with homegrownusa.club

**Comment by rickvidallon** [comment]
This confirms I have received your email-message and will reply ASAP. 
Thank you! 

Rick Vidallon
VISIONEFX 
site:   http://www.visionefx.net
email:  rick@visionefx.net
mobile: 757.619.6456 
office: 757.963.1787
