### ISSUE TITLE
Optimize paper-spinner styles

### ISSUE THREAD

**Issue by ltodorov** [PolymerElements/paper-spinner#71]
### Description
I would like to optimize your CSS styles. You can use color property instead of border-color because color is automatically inherited.

### Expected outcome
Use color property for the spinner-layer element and currectColor value for border-color of the pseudo elements. Remove !important rules.

**Comment by web-padawan** [comment]
What about [this line](https://github.com/PolymerElements/paper-spinner/blob/master/paper-spinner-styles.html#L255) containing `border-width`?

BTW, such things should be carefullty considered, e. g. when using `height: 1px` and `background` instead of `border-bottom` you might encounter some issued when zooming browser window AFAIK.

**Comment by ltodorov** [comment]
`color` not `background-color`. The main reason is that the default value for border-color is the current color value. You don't need to use `border-color: inherit` nor to use `!important`. I will provide a pull request and demo but it will take some time ;)

**Comment by keanulee** [comment]
I don't see how that would be better - so essentially `border-color: var(...)` is replaced with `color: var(...)`, and `border-color: inherit` with `border-color: currentColor` (still need `border-left-color: transparent !important` to style the open side).

**Comment by ltodorov** [comment]
Hey, I agree it won't be a huge improvement but you can remove one `border-color: inherit;` Also the last `border-color: currentColor;` is not needed because this is the default value of border-color.

**Comment by ltodorov** [comment]
Don't understand me wrongly. Your preloader component is amazing. I recently had a task to implement the same loader but without using Polymer so I used `color` instead of `border-color` inheritance.

**Comment by ltodorov** [comment]
Would you like to see a pull request with the changes?

**Comment by keanulee** [comment]
Good point - I didn't know that the default value of `border-color` is `currentColor`. PR's welcome :)
